config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root 'groups#index', as: :authenticated_root
  end

  unauthenticated do
    root "splash#index"
  end

  resources :groups, only: [:index, :new, :create] do
    resources :expenses, only: [:index, :new, :create]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  has_many :group_expenses
  has_many :groups, through: :group_expenses

  validates :name, presence: true, length: { in: 3..25 }
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  # has_and_belongs_to_many :groups

  has_many :group_expenses
  has_many :groups, through: :group_expenses

  attr_accessor :group_ids

  validates :name, presence: true, length: { in: 3..25 }
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  has_many :group_expenses
  has_many :expenses, through: :group_expenses

  validates :name, presence: true, length: { in: 3..25 }
  validates :icon, presence: true

  def total_amount
    expenses.sum(:amount)
  end
end

app/models/group_expense.rb
class GroupExpense < ApplicationRecord
  belongs_to :group
  belongs_to :expense
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, foreign_key: 'author_id'
  has_many :expenses, foreign_key: 'author_id'

  validates :name, presence: true, length: { in: 3..25 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!

  def index
    @group = Group.find(params[:group_id])
    @expenses = @group.expenses.order(created_at: :desc)
  end

  def new
    @groups = current_user.groups
    @group = Group.find(params[:group_id])
    @expense = @group.expenses.new
  end

  def create
    @group = Group.find(params[:group_id])
    @expense = @group.expenses.new(expense_params.merge(author: current_user))
    @expense.author = current_user

    selected_group_ids = params.dig(:expense, :group_ids) || []
    @expense.groups = Group.where(id: selected_group_ids)

    if @expense.save
      redirect_to group_expenses_path(@group), notice: 'Transaction was successfully created.'
    else
      flash[:alert] = 'Transaction could not be created.'
      render :new
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, group_ids: [])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = current_user.groups.order(created_at: :desc)
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.build(group_params)
    @group.author = current_user

    if @group.save
      redirect_to groups_path, notice: 'Category was successfully created'
    else
      flash.now[:alert] = 'Category could not be created'
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/expenses/index.html.erb
<div class="transactions">
  <div class="header">
    <%= link_to root_path do %>
      <%= image_tag 'back_arrow.svg' %>
    <% end %>
    <p>Transactions</p>
    <%= link_to new_group_expense_path do %>
      <%= image_tag 'plus.svg' %>
    <% end %>
  </div>

  <div class="transactions-total_amount">
    <p>Total Amount:</p>
    <p>₦<%= @group.total_amount %></p>
  </div>

  <div class="expenses">
    <% @expenses.each do |expense| %>
      <div class="expenses-expense">
        <span><%= expense.name %></span>
        <span>₦<%= expense.amount %></span>
      </div>
    <% end %>
  </div>

  <div class="btn-green">
    <%= link_to 'Add new transaction', new_group_expense_path, class: 'btn' %>
  </div>
</div>

app/views/expenses/new.html.erb
<%= form_with(model: [@group, @expense], local: true) do |f| %>
  <div class="header">
    <%= link_to group_expenses_path(@group) do %>
      <%= image_tag 'back_arrow.svg' %>
    <% end %>
    <p>Add new transaction</p>
    <div class="actions">
      <%= f.submit "Save", class: "header-btn" %>
    </div>
  </div>

  <div class="form">
    <div class="field">
      <%= f.text_field :name, autofocus: true, placeholder: 'Transaction name' %>
    </div>

    <div class="field">
      <%= f.number_field :amount, placeholder: 'Amount' %>
    </div>

    <div class="field">
      <p>Categories:</p>
      <% @groups.each do |group| %>
        <%= check_box_tag 'expense[group_ids][]', group.id %>
        <%= label_tag "expense_group_ids_#{group.id}", group.name %><br>
      <% end %>
    </div>
  </div>
<% end %>

app/views/groups/index.html.erb
<div class="categories">
  <div class="header">
    <%= link_to new_group_path do %>
      <%= image_tag 'plus.svg' %>
    <% end %>
    <p>Categories</p>
    <%= button_to destroy_user_session_path, method: :delete, class: "btn-logout" do %>
      <%= image_tag 'logout.svg' %>
    <% end %>
  </div>

  <div class="groups">
    <% @groups.each do |group| %>
      <%= link_to group_expenses_path(group) do %>
        <div class="groups-group">
          <div class="groups-group-left">
            <div class="groups-group-left-img">
              <img src="<%= image_path(group.icon) %>" alt="<%= group.icon %>" />
            </div>
            <div class="groups-group-left-name">
              <span><%= group.name %></span>
              <span><%= group.created_at.to_date %></span>
            </div>
          </div>
          <p>₦<%= group.total_amount %></p>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="btn-green">
    <%= link_to 'Add new category', new_group_path, class: 'btn' %>
  </div>
</div>

app/views/groups/new.html.erb
<%= form_with(model: @group, local: true) do |f| %>
  <div class="header">
    <%= link_to root_path do %>
      <%= image_tag 'back_arrow.svg' %>
      &nbsp;&nbsp;
    <% end %>
    <p>Add new category</p>
    <div class="actions">
      <%= f.submit "Save", class: "header-btn" %>
    </div>
  </div>

  <div class="form">
    <div class="field">
      <%= f.text_field :name, autofocus: true, placeholder: 'Category name' %>
    </div>

    <div class="field">
      <%= f.select :icon, options_for_select([
        ['Select an icon', ''],
        ['Rent', 'rent.png'],
        ['Transport', 'vehicles.png'],
        ['Shopping', 'shopping.png'],
        ['Tour', 'travel.png'],
        ['Grocery', 'grocery.png'],
        ['Others', 'other.png'],
      ], selected: @group.icon), {}, class: 'field-select' %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Budget Buddy</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200;300;700;800&family=Pacifico&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/splash/index.html.erb
<div class="splash">
  <div class="splash-logo logo">
    <span class="splash-logo-left">Budget</span><span>&nbsp;</span><span class="splash-logo-right">Buddy</span>
  </div>
  <div class="splash-links">
    <%= link_to 'Log in', new_user_session_path, class: 'btn btn-top' %>
    <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-bottom' %>
  </div>
</div>